export const comunasRM = [
  { value: "cerrillos", label: "Cerrillos" },
  { value: "la_reina", label: "La Reina" },
  { value: "pudahuel", label: "Pudahuel" },
  { value: "cerro_navia", label: "Cerro Navia" },
  { value: "las_condes", label: "Las Condes" },
  { value: "las_condes", label: "Las Condes" },
  { value: "quilicura", label: "Quilicura" },
  { value: "conchali", label: "Conchalí" },
  { value: "lo_barnechea", label: "Lo Barnechea" },
  { value: "quinta_normal", label: "Quinta Normal" },
  { value: "el_bosque", label: "El Bosque" },
  { value: "lo_espejo", label: "Lo Espejo" },
  { value: "recoleta", label: "Recoleta" },
  { value: "estacion_central", label: "Estación Central" },
  { value: "lo_prado", label: "Lo Prado" },
  { value: "renca", label: "Renca" },
  { value: "huechuraba", label: "Huechuraba" },
  { value: "macul", label: "Macul" },
  { value: "san_miguel", label: "San Miguel" },
  { value: "independencia", label: "Independencia" },
  { value: "maipu", label: "Maipú" },
  { value: "san_joaquin", label: "San Joaquín" },
  { value: "la_cisterna", label: "La Cisterna" },
  { value: "nunoa", label: "Ñuñoa" },
  { value: "san_ramon", label: "San Ramón" },
  { value: "la_florida", label: "La Florida" },
  { value: "pedro_aguirre_cerda", label: "Pedro Aguirre Cerda" },
  { value: "santiago_centro", label: "Santiago (Centro)" },
  { value: "la_pintana", label: "La Pintana" },
  { value: "penalolen", label: "Peñalolén" },
  { value: "vitacura", label: "Vitacura" },
  { value: "la_granja", label: "La Granja" },
  { value: "providencia", label: "Providencia" },
];
